/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DataHandling.dataReadIn;
import UserObj.user;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.ArrayList;

/**
 *
 * @author Block
 */
public class addAndRemoveDoctorAccountviaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form addAndRemoveDoctorAccountviaAdmin
     */
    public addAndRemoveDoctorAccountviaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password4 = new javax.swing.JTextField();
        password6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameIn = new javax.swing.JTextField();
        passwordIn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        firstnameIn = new javax.swing.JTextField();
        lastnameIn = new javax.swing.JTextField();
        mobileNumberIn = new javax.swing.JTextField();
        addresslineIn = new javax.swing.JTextField();
        ageIn = new javax.swing.JTextField();
        genderIn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("add or remove doctor account");

        jButton2.setText("add account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("remove account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("username");

        jLabel3.setText("password");

        jLabel4.setText("firstname");

        jLabel5.setText("lastname");

        jLabel6.setText("mobile number");

        jLabel7.setText("addressline");

        jLabel8.setText("age");

        jLabel9.setText("gender");

        firstnameIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameInActionPerformed(evt);
            }
        });

        jLabel10.setText("to remove account you only need to enter username and password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genderIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(ageIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(addresslineIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mobileNumberIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastnameIn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(firstnameIn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordIn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usernameIn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(firstnameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lastnameIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mobileNumberIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(addresslineIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ageIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(genderIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adminLogedInScreen open = new adminLogedInScreen();
        open.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String username = usernameIn.getText();
        String password = passwordIn.getText();
        String firstname = firstnameIn.getText();
        String lastname = lastnameIn.getText();
        String mobilePhoneNumber = mobileNumberIn.getText();
        String addressline = addresslineIn.getText();
        String age = ageIn.getText();
        String gender = genderIn.getText();
        String ratingsHolder = "ratings:";
        String commentsholder = "Comments";
        String adminFeedbackholder = "adminFeedBack";       
        
         try{
            BufferedWriter out = new BufferedWriter(new FileWriter("./checks\\approvedDoctors.txt", true));
            out.newLine();
            out.newLine();
            out.write(username);
            out.newLine();
            out.write(password);
            out.newLine();
            out.write(firstname);
            out.newLine();
            out.write(lastname);
            out.newLine();
            out.write(mobilePhoneNumber);
            out.newLine();
            out.write(addressline);
            out.newLine();
            out.write(age);
            out.newLine();
            out.write(gender);
            out.newLine();
            out.write(ratingsHolder);
            out.newLine();
            out.write(commentsholder);
            out.newLine();
            out.write(adminFeedbackholder);
            out.newLine();
            out.close();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void firstnameInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameInActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        ArrayList<user> currentDoctor1 = new ArrayList<user>();
        dataReadIn data = new dataReadIn();
        try{
        data.readCurrentDoctors(currentDoctor1);
        }
        catch(Exception e){
                e.printStackTrace();
            }
        Object[] currentDoctor = currentDoctor1.toArray();
        int length = currentDoctor.length;
        String[] username1 = new String[length], password1 = new String[length];
            for (int i = 0; i < length; i++) {
                String name = ((UserObj.doctorObj)currentDoctor[i]).getUserId();
                String pass = ((UserObj.doctorObj)currentDoctor[i]).getPassword();
                username1[i] = name;
                password1[i] = pass;
            }
        int a = 0;
        boolean userisTrue;
        boolean passisTrue;
        
        while( a < length){
            if(username1[a].equals(usernameIn.getText())){
                userisTrue = true;
            }
            else{
                userisTrue = false;
            }
            if(password1[a].equals(passwordIn.getText())){
                passisTrue = true;
            }
            else{
                passisTrue = false;
            }
            if(Boolean.TRUE.equals(passisTrue) && Boolean.TRUE.equals(userisTrue)){
                data.removeDoctor(currentDoctor1.get(a), currentDoctor1);
                try{
                   BufferedWriter clear = new BufferedWriter(new FileWriter("./checks\\approvedDoctors.txt", false));
                    clear.newLine();
                }
                catch(Exception e){
                e.printStackTrace();
                }
                if(length != 1){
                    length = length - 1;
                }
                    
                    for (int l = 0; l < length; l++) {
                        currentDoctor = currentDoctor1.toArray();
                        String userId = ((UserObj.doctorObj)currentDoctor[l]).getUserId();
                        String password = ((UserObj.doctorObj)currentDoctor[l]).getPassword();
                        String firstName = ((UserObj.doctorObj)currentDoctor[l]).getFirstname();
                        String lastName = ((UserObj.doctorObj)currentDoctor[l]).getLastname();
                        String mobilenumber = ((UserObj.doctorObj)currentDoctor[l]).getMobileNumber();
                        String addressline = ((UserObj.doctorObj)currentDoctor[l]).getAddressline();
                        String age = ((UserObj.doctorObj)currentDoctor[l]).getAge();
                        String gender = ((UserObj.doctorObj)currentDoctor[l]).getGender();
                        String ratings = ((UserObj.doctorObj)currentDoctor[l]).getRatings();
                        String comments = ((UserObj.doctorObj)currentDoctor[l]).getComments();
                        String adminFeedback = ((UserObj.doctorObj)currentDoctor[l]).getAdminFeedback();
                               
                        try{
                            BufferedWriter out = new BufferedWriter(new FileWriter("./checks\\approvedDoctors.txt", true));
                            out.newLine();
                            out.write(userId);
                            out.newLine();
                            out.write(password);
                            out.newLine();
                            out.write(firstName);
                            out.newLine();
                            out.write(lastName);
                            out.newLine();
                            out.write(mobilenumber);
                            out.newLine();
                            out.write(addressline);
                            out.newLine();
                            out.write(age);
                            out.newLine();
                            out.write(gender);
                            out.newLine();
                            out.write(ratings);
                            out.newLine();
                            out.write(comments);
                            out.newLine();
                            out.write(adminFeedback);
                            out.newLine();
                            out.close();
                            
                    }
                    catch(Exception e){
                        e.printStackTrace();
                    }
                    
                }
            }
            a = a + 1;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAndRemoveDoctorAccountviaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAndRemoveDoctorAccountviaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAndRemoveDoctorAccountviaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAndRemoveDoctorAccountviaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAndRemoveDoctorAccountviaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresslineIn;
    private javax.swing.JTextField ageIn;
    private javax.swing.JTextField firstnameIn;
    private javax.swing.JTextField genderIn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastnameIn;
    private javax.swing.JTextField mobileNumberIn;
    private javax.swing.JTextField password4;
    private javax.swing.JTextField password6;
    private javax.swing.JTextField passwordIn;
    private javax.swing.JTextField usernameIn;
    // End of variables declaration//GEN-END:variables
}
